version: '2'
services:
  namenode:
    image: mithucste30/hadoop_namenode
    volumes:
      - $PWD/conf.cdh5:/etc/hadoop/conf.cdh5
    hostname: master

  secondary_namenode:
    image: mithucste30/hadoop_secondary_namenode
    links:
      - namenode:master
    depends_on:
      - namenode
    volumes:
      - $PWD/conf.cdh5:/etc/hadoop/conf.cdh5

  data_node:
    image: mithucste30/hadoop_datanode
    links:
      - namenode:master
    depends_on:
      - secondary_namenode
    volumes:
      - $PWD/conf.cdh5:/etc/hadoop/conf.cdh5
