version: '2'
services:
  master:
    image: hadoop_master
  slave1:
    image: hadoop_slave_01
    links:
     - master
    depends_on:
     - master

  slave2:
    image: hadoop_slave_02
    links:
     - master
    depends_on:
     - slave1
